language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
deploy:
 provider: heroku
 api_key: 25471dfb-a8b3-421b-9992-2770f07376a8
 app: calm-caverns-10083
 run: "rake db:migrate"
 on:
  branch: main_or_master